### ISSUE TITLE
crashes due to service response?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/antares-backend#10]
```python
mkdir: created directory '/tmp/xdg_cache_home'
mkdir: created directory '/tmp/xdg_cache_home/astropy'
total 489312
drwxrws--- 2 root        16384 Jul 16  2021 lost+found
-rw-rw-r-- 1 antares 174173064 Oct 10 16:16 oda-antares-868d4b6866-s2ldz
drwxrwsr-x 3 root         4096 Oct 10 16:26 .
-rw-rw-r-- 1 antares 326847419 Mar 21 08:02 oda-antares-868d4b6866-t69kf
drwxr-xr-x 1 root         4096 Mar 21 09:03 ..
INFO:root:Loaded catalog from data center.
INFO:root:Loaded entry ana20_01_bkg as <class 'openkm3.dataclasses.Function'>.
INFO:root:Loaded entry ana20_01_acc as <class 'openkm3.dataclasses.LookUpTable'>.
Traceback (most recent call last):
  File "/usr/local/bin/populate_data.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/antares-backend/bin/populate_data.py", line 63, in <module>
    main()
  File "/antares-backend/bin/populate_data.py", line 48, in main
    data = store.get('ana20_01_vo')
  File "/usr/local/lib/python3.8/dist-packages/openkm3/store.py", line 228, in get
    kobject = SCSServiceVO.from_resource(resinfo, data_local, loadoption)
  File "/usr/local/lib/python3.8/dist-packages/openkm3/dataclasses.py", line 29, in from_resource
    newone._set_meta()
  File "/usr/local/lib/python3.8/dist-packages/openkm3/dataclasses.py", line 344, in _set_meta
    self.accessInfo = from_json(self.meta["accessInfo"])
  File "/usr/local/lib/python3.8/dist-packages/openkm3/dataclasses.py", line 440, in from_json
    return json.loads(instring.replace("'", '"'))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by dsavchenko** [comment]
The problem originates from some wrong configuration of the storage used by https://git.km3net.de/open-data/openkm3

As these data are small and static, let's not populate from the storage from now, just have data in the repo instead https://github.com/oda-hub/antares-backend/pull/11

**Comment by dsavchenko** [comment]
I merged the workaround, but not sure, if this issue should be closed. It's still there, though it is not our issue in fact
