### ISSUE TITLE
still antares error?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/antares-backend#13]
```python
drwxrws--- 2 root 16384 Mar 22 13:42 lost+found
drwxrwsr-x 3 root  4096 Mar 22 13:42 .
drwxr-xr-x 1 root  4096 Mar 22 13:44 ..
INFO:root:Loaded catalog from data center.
INFO:root:Loaded entry ana20_01_bkg as <class 'openkm3.dataclasses.Function'>.
INFO:root:Loaded entry ana20_01_acc as <class 'openkm3.dataclasses.LookUpTable'>.
Traceback (most recent call last):
  File "/usr/local/bin/populate_data.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/antares-backend/bin/populate_data.py", line 63, in <module>
    main()
  File "/antares-backend/bin/populate_data.py", line 48, in main
    data = store.get('ana20_01_vo')
  File "/usr/local/lib/python3.8/dist-packages/openkm3/store.py", line 228, in get
    kobject = SCSServiceVO.from_resource(resinfo, data_local, loadoption)
  File "/usr/local/lib/python3.8/dist-packages/openkm3/dataclasses.py", line 29, in from_resource
    newone._set_meta()
  File "/usr/local/lib/python3.8/dist-packages/openkm3/dataclasses.py", line 344, in _set_meta
    self.accessInfo = from_json(self.meta["accessInfo"])
  File "/usr/local/lib/python3.8/dist-packages/openkm3/dataclasses.py", line 440, in from_json
    return json.loads(instring.replace("'", '"'))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by volodymyrss** [comment]
even after this https://github.com/oda-hub/antares-backend/pull/12

**Comment by dsavchenko** [comment]
Is it in k8s? Try with https://github.com/oda-hub/antares-chart/pull/1 
Sorry, I forgot to change the config also there

**Comment by volodymyrss** [comment]
ah ok, that works. it's not master so was not deployed. but now it's good!

**Comment by dsavchenko** [comment]
Antares in staging produces error again. @volodymyrss could you check the logs?

**Comment by volodymyrss** [comment]
was not deployed, sorry. need to sort out antares deployment to make it regular like other pieces but only next week. 

now it should work, please check
